In [2]:
import numpy as np

In [3]:
k= np.array([1,2,3,4])

In [4]:
k

array([1, 2, 3, 4])

In [5]:
type(k)

numpy.ndarray

In [6]:
k2=np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
k2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
k3=np.zeros((2,3))
k3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
k4=np.full((3,3),7)

In [10]:
k4

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [11]:
np.arange(2,13)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [13]:
np.random.randint(1,100,5)

array([93, 57, 57, 14, 77])

In [14]:
k2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
k2.shape

(1, 8)

In [18]:
k2.shape=(1,8)
k2

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [19]:
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])

In [20]:
np.sum((n1,n2))

36

In [21]:
l=np.sum((n1,n2),axis=0) 
l

array([ 6,  8, 10, 12])

In [22]:
k=np.sum((n1,n2),axis=1)
k

array([10, 26])

In [26]:
k.shape

(2,)

In [24]:
l.shape

(4,)

In [40]:
n1=np.array([1,2,3,4])
n2=np.array([1,2,3,4])

In [45]:
n3=np.vstack((n1,n2))
n4=np.column_stack((n1,n2))
n5=np.hstack((n1,n2))
n6=np.row_stack((n1,n2))
print(n3)
print(n4)
print(n5)
print(n6)

[[1 2 3 4]
 [1 2 3 4]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[1 2 3 4 1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]]


In [49]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.random.rand(3)

array([0.68781226, 0.0491303 , 0.01005552])

In [53]:
np.random.rand(3,3)

array([[0.09149582, 0.13037596, 0.18104534],
       [0.59130911, 0.67335778, 0.8109499 ],
       [0.9288126 , 0.74914687, 0.1264406 ]])

In [54]:
np.random.randn(3)

array([1.08387701, 0.80107053, 0.55231518])

In [57]:
np.random.randn(2,2)

array([[-0.11064558,  1.10696805],
       [ 0.91224927, -0.04625821]])

In [58]:
np.random.randint(1,100)

75

In [59]:
np.random.randint(1,100,4)

array([34, 22, 73, 83])

In [61]:
arr=np.random.randint(1,100,(4,2))

In [62]:
arr

array([[88, 63],
       [64, 33],
       [72,  3],
       [35,  7]])

In [63]:
arr.reshape(2,4)

array([[88, 63, 64, 33],
       [72,  3, 35,  7]])

In [64]:
arr.transpose()

array([[88, 64, 72, 35],
       [63, 33,  3,  7]])

In [65]:
arr

array([[88, 63],
       [64, 33],
       [72,  3],
       [35,  7]])

In [66]:
arr.max()

88

In [67]:
arr.min()

3

In [68]:
arr.argmax()

0

In [70]:
arr.argmin()

5

In [77]:
arr.mean(axis=0)

array([64.75, 26.5 ])

In [76]:
arr

array([[88, 63],
       [64, 33],
       [72,  3],
       [35,  7]])

In [78]:
arr.mean(axis=1)

array([75.5, 48.5, 37.5, 21. ])

In [82]:
arr[2][1]

3

In [83]:
arr[2,1]

3

In [84]:
arr2=np.arange(0,11)

In [85]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr2[8]

8

In [89]:
arr2[0:5]=100

In [90]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [98]:
soa=arr2[:5]
soa

array([100, 100, 100, 100, 100])

In [99]:
soa[:]=99

In [100]:
soa

array([99, 99, 99, 99, 99])

In [101]:
arr2

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

The changes made to soa are automatically reflected in arr2 as

The reason above the changes that have happened is that numpy doesnot make copies of array and assign it to soa but the soa points to original memmory location where arr2 elements were located so when we make changes to those elements those changes get reflected in our main arr2

In [102]:
arr2

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [105]:
arr3=arr2.copy()

In [106]:
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

so to avoide problem of overwritting the original array what we can do is make a copy of original array and then we can make assignment and changes with respect to this arr


In [108]:
arr_2d=np.arange(5,50,5)

In [113]:
arr_2d=arr_2d.reshape(3,3)

In [114]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [116]:
arr_2d[0][0]

5

In [117]:
arr_2d[0][1]

10

In [118]:
arr_2d[0,1]

10

arr_2d[:2,:2]

# conditinal selection

In [122]:
qw=np.arange(1,11)

In [123]:
qw

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
bool_arr=qw>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [133]:
qw[bool_arr]

array([ 6,  7,  8,  9, 10])

In [137]:
qw.all()

True

In [138]:
sh=np.arange(0,11)

In [139]:
sh

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [140]:
 se= sh+sh

In [141]:
se

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [142]:
me=sh*sh

In [143]:
me

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [144]:
np.sqrt(sh)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [145]:
sh

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
np.where((sh>2) & (sh<8))

(array([3, 4, 5, 6, 7], dtype=int32),)